<#
.SYNOPSIS
    One-command build & flash for the Plai firmware (ESP-IDF 5.5.x / esp32s3 / M5Stack Cardputer).

.DESCRIPTION
    Run `.\flash.ps1` and the firmware ends up on the device. The script is idempotent:
    it performs any missing one-time setup (clone Meshtastic protobufs, create the nanopb
    generator venv, generate the protobuf code), activates the ESP-IDF environment, builds,
    auto-detects the device's COM port, warns before it wipes the NVS mesh keys, then flashes.

    See the "Building from Source" section of README.md for the manual steps this automates.

.EXAMPLE
    .\flash.ps1
    First-time / full flash. Sets up what's missing, builds, prompts before wiping NVS, flashes.

.EXAMPLE
    .\flash.ps1 -AppOnly
    Routine update that flashes only the app partition and KEEPS the device's mesh keys.

.EXAMPLE
    .\flash.ps1 -Yes -Monitor
    Full flash without the confirmation prompt, then open the serial monitor.

.NOTES
    Windows PowerShell 5.1+. If execution is blocked:
        powershell -ExecutionPolicy Bypass -File .\flash.ps1
#>

[CmdletBinding()]
param(
    [string] $Port,                          # "COM4"; auto-detect (USB VID 303A) when omitted
    [switch] $AppOnly,                        # idf.py app-flash (app only; preserves NVS keys)
    [switch] $Full,                           # explicit full flash (default when neither set)
    [switch] $Monitor,                        # open idf.py monitor after flashing (exit Ctrl+])
    [switch] $Regen,                          # force-regenerate the nanopb protobuf code
    [switch] $Clean,                          # idf.py fullclean before building
    [switch] $SetupOnly,                      # one-time setup only; no build/flash
    [Alias('BuildOnly')][switch] $NoFlash,    # build (and set up) but do not flash
    [Alias('Force')]   [switch] $Yes,         # non-interactive: skip the NVS-wipe confirmation
    [string] $SysPython,                      # system python.exe used to create tools\protovenv
    [switch] $Help
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- Constants -------------------------------------------------------------------------------

$RepoRoot = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
$ProtobufsUrl = 'https://github.com/meshtastic/protobufs.git'

# Stamped into any tools\activate-idf.ps1 we generate, so we can tell ours apart from a
# hand-written one and never clobber a deliberate user override.
$AutoGenMarker = '# Auto-generated by flash.ps1'

# The ESP-IDF install resolved from the EIM manifest (eim_idf.json). Populated in the
# orchestration block and reused for activation + the git / Python clean-machine fallbacks.
$script:IdfInstall = $null

# Last-ditch fallback, used ONLY when no eim_idf.json manifest is found anywhere (e.g. a non-EIM
# install). These are the Espressif installer's Windows defaults for v5.5.4; manifest discovery
# (Get-IdfInstallsFromEim) supersedes them on any normal install, regardless of version or drive.
$IdfDefaults = @{
    Profile   = 'C:\Espressif\tools\Microsoft.v5.5.4.PowerShell_profile.ps1'
    IdfPath   = 'C:\esp\v5.5.4\esp-idf'
    ToolsPath = 'C:\Espressif\tools'
    PyEnvPath = 'C:\Espressif\tools\python\v5.5.4\venv'
}

# --- Small output helpers --------------------------------------------------------------------

function Step    { param([string]$m) Write-Host "`n==> $m" -ForegroundColor Cyan }
function Detail  { param([string]$m) Write-Host "    $m"   -ForegroundColor DarkGray }
function Good    { param([string]$m) Write-Host "    $m"   -ForegroundColor Green }
function Caution { param([string]$m) Write-Host "    $m"   -ForegroundColor Yellow }

# Throw if the most recent native command set a non-zero exit code. (Native exes set
# $LASTEXITCODE; PowerShell functions/cmdlets do not, so this reads the real last result.)
function Assert-Exit {
    param([Parameter(Mandatory)][string] $What)
    if ($LASTEXITCODE -ne 0) { throw "$What failed (exit code $LASTEXITCODE)." }
}

function Show-Help {
@"
flash.ps1 - one-command build & flash for Plai (ESP-IDF / esp32s3 / M5Stack Cardputer)

USAGE
  .\flash.ps1 [options]

  With no options:  set up (if needed) -> build -> detect port -> confirm -> FULL flash.

OPTIONS
  -Port <COMx>    Target serial port. Auto-detected (USB VID 303A) when omitted.
  -AppOnly        Flash only the app partition (idf.py app-flash). Preserves NVS / mesh keys.
  -Full           Force a full flash (the default when neither -AppOnly nor -Full is given).
  -Monitor        Open the serial monitor after flashing (exit with Ctrl+]).
  -Regen          Force-regenerate the nanopb protobuf code.
  -Clean          Run 'idf.py fullclean' before building.
  -SetupOnly      Only do one-time setup (protobufs + generator venv + codegen); no build/flash.
  -NoFlash        Build (and set up) but do not flash. Alias: -BuildOnly.
  -Yes            Non-interactive: skip the NVS-wipe confirmation. Alias: -Force.
  -SysPython <p>  Path to a system python.exe used to create tools\protovenv.
  -Help           Show this help.

EXAMPLES
  .\flash.ps1                   First-time / full flash (prompts before wiping NVS)
  .\flash.ps1 -AppOnly          Routine update that keeps your mesh keys
  .\flash.ps1 -Yes -Monitor     Full flash without prompting, then watch logs
  .\flash.ps1 -NoFlash          Just build
  .\flash.ps1 -Regen -NoFlash   Regenerate protobufs and build

NOTES
  - NVS holds your mesh/channel + security keys. A FULL flash resets NVS to nvs.csv defaults
    (keys wiped). Back up first on-device via Settings -> Export, or use -AppOnly.
  - If PowerShell blocks the script:  powershell -ExecutionPolicy Bypass -File .\flash.ps1
"@ | Write-Host
}

# --- Prerequisite discovery ------------------------------------------------------------------

function Assert-RepoRoot {
    foreach ($m in @('CMakeLists.txt', 'partitions.csv', 'nvs.csv', 'main\CMakeLists.txt')) {
        if (-not (Test-Path (Join-Path $RepoRoot $m))) {
            throw "This doesn't look like the Plai repo root (missing '$m'). Keep flash.ps1 in the repo root."
        }
    }
}

# Does $Exe run as a working Python? (Avoids the noisy Windows Store alias stub.)
function Test-PythonExe {
    param([string] $Exe)
    if (-not $Exe) { return $false }
    try {
        $null = & $Exe --version
        return ($LASTEXITCODE -eq 0)
    }
    catch { return $false }
}

# Locate a Python to build tools\protovenv. Prefer a standalone system Python; never pip-install
# into the ESP-IDF venv (kept pristine). Resolve this BEFORE activation, which prepends the IDF
# venv to PATH. As a last resort on a Python-less machine it returns the ESP-IDF base interpreter,
# which is only ever used to spawn a SEPARATE venv (so the IDF env stays untouched). $null if none.
function Get-SystemPython {
    if ($SysPython) {
        if ((Test-Path $SysPython) -and (Test-PythonExe $SysPython)) { return (Resolve-Path $SysPython).Path }
        throw "-SysPython '$SysPython' is not a working Python interpreter."
    }
    $base = Join-Path $env:LOCALAPPDATA 'Programs\Python'
    if (Test-Path $base) {
        $dirs = @(Get-ChildItem -Path $base -Filter 'Python*' -Directory -ErrorAction SilentlyContinue |
                  Sort-Object Name -Descending)
        foreach ($d in $dirs) {
            $exe = Join-Path $d.FullName 'python.exe'
            if ((Test-Path $exe) -and (Test-PythonExe $exe)) { return $exe }
        }
    }
    if (Get-Command py -ErrorAction SilentlyContinue) {
        try {
            $exe = & py -3 -c "import sys; print(sys.executable)" | Select-Object -First 1
            if ($LASTEXITCODE -eq 0 -and $exe -and (Test-Path $exe) -and (Test-PythonExe $exe)) { return $exe }
        }
        catch { }
    }
    $pyc = Get-Command python -ErrorAction SilentlyContinue
    if ($pyc -and $pyc.Source -and ($pyc.Source -notmatch 'WindowsApps') -and (Test-PythonExe $pyc.Source)) {
        return $pyc.Source
    }
    # Last resort (clean machine with no standalone Python): the ESP-IDF base interpreter. We only
    # use it to create a SEPARATE venv (tools\protovenv), never to install into the IDF env.
    if ($script:IdfInstall -and $script:IdfInstall.Python -and
        (Test-Path $script:IdfInstall.Python) -and (Test-PythonExe $script:IdfInstall.Python)) {
        Detail "No standalone Python found; will bootstrap tools\protovenv from the ESP-IDF Python."
        return $script:IdfInstall.Python
    }
    return $null
}

# --- ESP-IDF discovery (EIM manifest) --------------------------------------------------------

# Safe property read for objects parsed by ConvertFrom-Json (StrictMode-clean: a missing field
# returns $null instead of throwing).
function Get-JsonProp {
    param($Obj, [string] $Name)
    if ($null -ne $Obj -and ($Obj.PSObject.Properties.Name -contains $Name)) { return $Obj.$Name }
    return $null
}

# Roots where an Espressif install (EIM / installer) may live. Drives beyond C: are scanned too,
# so a non-default install location still resolves.
function Get-EspressifRoots {
    $roots = New-Object System.Collections.Generic.List[string]
    if ($env:IDF_TOOLS_PATH) { $roots.Add($env:IDF_TOOLS_PATH) }
    $roots.Add('C:\Espressif')
    $roots.Add('C:\esp')
    if ($env:LOCALAPPDATA) { $roots.Add((Join-Path $env:LOCALAPPDATA 'Espressif')) }
    if ($env:USERPROFILE)  { $roots.Add((Join-Path $env:USERPROFILE '.espressif')) }
    if ($env:USERPROFILE)  { $roots.Add((Join-Path $env:USERPROFILE 'esp')) }
    try {
        foreach ($d in [System.IO.DriveInfo]::GetDrives()) {
            if ($d.DriveType -eq 'Fixed' -and $d.Name -ne 'C:\') {
                $roots.Add((Join-Path $d.Name 'Espressif'))
                $roots.Add((Join-Path $d.Name 'esp'))
            }
        }
    }
    catch { }
    $roots | Where-Object { $_ } | Select-Object -Unique
}

# Parse every discoverable EIM manifest (eim_idf.json) into install records. EIM writes one
# manifest per install root listing each version's exact paths - far more reliable than guessing.
function Get-IdfInstallsFromEim {
    $installs = @()
    $seen = @{}
    foreach ($root in (Get-EspressifRoots)) {
        foreach ($rel in @('eim_idf.json', 'tools\eim_idf.json')) {
            $manifest = Join-Path $root $rel
            if (-not (Test-Path $manifest)) { continue }
            $full = (Resolve-Path $manifest).Path
            if ($seen.ContainsKey($full)) { continue }
            $seen[$full] = $true
            try { $j = Get-Content -Path $full -Raw -Encoding UTF8 | ConvertFrom-Json }
            catch { Detail "Ignoring unreadable manifest: $full"; continue }

            $selectedId = Get-JsonProp $j 'idfSelectedId'
            $gitPath = Get-JsonProp $j 'gitPath'
            foreach ($e in @(Get-JsonProp $j 'idfInstalled')) {
                $idfPath = Get-JsonProp $e 'path'
                $actScript = Get-JsonProp $e 'activationScript'
                if (-not $idfPath -or -not $actScript) { continue }
                $py = Get-JsonProp $e 'python'
                $pyEnv = if ($py) { Split-Path -Parent (Split-Path -Parent $py) } else { $null }
                $installs += [pscustomobject]@{
                    Version   = ([string](Get-JsonProp $e 'name') -replace '^v', '')
                    Profile   = [string]$actScript
                    IdfPath   = [string]$idfPath
                    ToolsPath = [string](Get-JsonProp $e 'idfToolsPath')
                    PyEnvPath = $pyEnv
                    Python    = [string]$py
                    GitPath   = [string]$gitPath
                    Selected  = ((Get-JsonProp $e 'id') -eq $selectedId)
                    Source    = $full
                }
            }
        }
    }
    $installs
}

# Pick the best install: it must exist on disk; prefer 5.5.x, then the EIM-selected one, then the
# highest version. Returns $null when nothing usable is found.
function Select-BestIdf {
    param([object[]] $Installs)
    if (-not $Installs -or $Installs.Count -eq 0) { return $null }

    $valid = @($Installs | Where-Object { (Test-Path $_.Profile) -and (Test-Path $_.IdfPath) })
    if ($valid.Count -eq 0) { return $null }

    $pref = @($valid | Where-Object { $_.Version -like '5.5.*' })
    $pool = if ($pref.Count -gt 0) { $pref } else { $valid }

    $pool | Sort-Object `
        @{ Expression = { [bool]$_.Selected }; Descending = $true }, `
        @{ Expression = { try { [version]$_.Version } catch { [version]'0.0' } }; Descending = $true } |
    Select-Object -First 1
}

# --- ESP-IDF activation ----------------------------------------------------------------------

# Write a local (gitignored) tools\activate-idf.ps1 for the given install record. The EIM profile
# sets PATH + the idf.py alias and activates the venv, but does NOT export these three vars
# (it only prints them), so we set them here - idf.py and the CMake build need them.
function New-ActivateIdfHelper {
    param(
        [Parameter(Mandatory)][string] $Path,
        [Parameter(Mandatory)][object] $Install
    )
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $content = @"
$AutoGenMarker from $($Install.Source)
# Activates ESP-IDF $($Install.Version). Regenerated automatically; edit at your own risk (a
# hand-written file without the line above is treated as a user override and left untouched).
. "$($Install.Profile)" *>`$null
`$env:IDF_PATH            = "$($Install.IdfPath)"
`$env:IDF_TOOLS_PATH      = "$($Install.ToolsPath)"
`$env:IDF_PYTHON_ENV_PATH = "$($Install.PyEnvPath)"
"@
    Set-Content -Path $Path -Value $content -Encoding UTF8
}

# Return the path to a .ps1 the caller must dot-source (at SCRIPT scope) to put idf.py on PATH,
# or $null if idf.py is already available. Throws with guidance if it cannot be resolved.
# Consumes $script:IdfInstall (resolved earlier in the orchestration block).
function Resolve-ActivationScript {
    if (Get-Command idf.py -ErrorAction SilentlyContinue) {
        Detail "ESP-IDF already active ($((Get-Command idf.py).Source))."
        return $null
    }

    $helper = Join-Path $RepoRoot 'tools\activate-idf.ps1'
    $existing = if (Test-Path $helper) { Get-Content -Path $helper -Raw -ErrorAction SilentlyContinue } else { $null }

    # A hand-written helper (no auto-gen marker) is a deliberate override - honor it untouched.
    if ($existing -and ($existing -notmatch [regex]::Escape($AutoGenMarker))) {
        Detail "Using hand-written tools\activate-idf.ps1"
        return $helper
    }

    # Primary: (re)generate the helper from the discovered EIM install. Version/location-agnostic.
    if ($script:IdfInstall) {
        Detail "Discovered ESP-IDF $($script:IdfInstall.Version) via $($script:IdfInstall.Source)"
        New-ActivateIdfHelper -Path $helper -Install $script:IdfInstall
        return $helper
    }

    # A helper we generated on a previous run (discovery failed now, but it worked before).
    if ($existing) {
        Detail "Reusing previously generated tools\activate-idf.ps1"
        return $helper
    }

    # Last-ditch: the built-in hardcoded defaults, if that profile happens to exist on this box.
    if (Test-Path $IdfDefaults.Profile) {
        Detail "No EIM manifest found; falling back to built-in defaults."
        $script:IdfInstall = [pscustomobject]@{
            Version   = '5.5.4'
            Profile   = $IdfDefaults.Profile
            IdfPath   = $IdfDefaults.IdfPath
            ToolsPath = $IdfDefaults.ToolsPath
            PyEnvPath = $IdfDefaults.PyEnvPath
            Python    = (Join-Path $IdfDefaults.PyEnvPath 'Scripts\python.exe')
            GitPath   = $null
            Selected  = $true
            Source    = '(built-in defaults)'
        }
        New-ActivateIdfHelper -Path $helper -Install $script:IdfInstall
        return $helper
    }

    # A plain framework export.ps1 (non-EIM: offline installer / VS Code / manual checkout).
    if ($env:IDF_PATH -and (Test-Path (Join-Path $env:IDF_PATH 'export.ps1'))) {
        Detail "Using `$env:IDF_PATH\export.ps1 (legacy)."
        return (Join-Path $env:IDF_PATH 'export.ps1')
    }

    throw @"
Could not find or activate ESP-IDF, so the firmware can't be built.

Most likely cause: ESP-IDF isn't installed on this machine yet.
  This project needs ESP-IDF v5.5.x for the esp32s3 target (tested with 5.5.4). On Windows the
  simplest install is the ESP-IDF Installation Manager (EIM):
      https://docs.espressif.com/projects/esp-idf/en/v5.5.4/esp32s3/get-started/
  See the "Building from Source" section of README.md for the project's prerequisites.

If ESP-IDF IS already installed, flash.ps1 just couldn't locate it. It looked for, in order:
  - idf.py already on PATH (i.e. you launched this from an ESP-IDF shell)
  - a hand-written tools\activate-idf.ps1 in this repo
  - an EIM manifest (eim_idf.json) under any of:
      $((Get-EspressifRoots) -join "`n      ")
  - the built-in default profile: $($IdfDefaults.Profile)
  - `$env:IDF_PATH\export.ps1
  Fixes: open an "ESP-IDF PowerShell" shell and re-run flash.ps1 from there; or run your install's
  export.ps1 in this shell first; or create tools\activate-idf.ps1 that dot-sources your ESP-IDF
  profile and sets IDF_PATH, IDF_TOOLS_PATH and IDF_PYTHON_ENV_PATH.
"@
}

# --- Protobuf setup (idempotent) -------------------------------------------------------------

function Ensure-Protos {
    $protoDir  = Join-Path $RepoRoot 'protobufs'
    $protoGlob = Join-Path $RepoRoot 'protobufs\meshtastic\*.proto'
    $genDir    = Join-Path $RepoRoot 'main\meshtastic'
    $venvDir   = Join-Path $RepoRoot 'tools\protovenv'
    $venvPy    = Join-Path $venvDir 'Scripts\python.exe'

    # 1. Proto sources (the .gitmodules submodule is broken; clone directly).
    $protoFiles = @(Get-ChildItem -Path $protoGlob -ErrorAction SilentlyContinue)
    if ($protoFiles.Count -eq 0) {
        if (Test-Path $protoDir) {
            throw "protobufs\ exists but has no meshtastic\*.proto. Delete protobufs\ and re-run."
        }
        if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
            throw "git not found on PATH; it's needed to clone the Meshtastic protobufs."
        }
        Step "Cloning Meshtastic protobufs"
        git clone --depth 1 $ProtobufsUrl $protoDir
        Assert-Exit "git clone protobufs"
        $protoFiles = @(Get-ChildItem -Path $protoGlob -ErrorAction SilentlyContinue)
    }
    else {
        Detail "Proto sources present ($($protoFiles.Count) .proto files)."
    }

    # 2. Isolated nanopb generator venv (grpcio-tools provides protoc; keeps the IDF venv pristine).
    if (-not (Test-Path $venvPy)) {
        if (-not $script:SystemPython) {
            throw "No system Python found to create tools\protovenv. Install Python 3, or pass -SysPython <python.exe>."
        }
        Step "Creating protobuf generator venv (tools\protovenv)"
        Detail "Using system Python: $script:SystemPython"
        if (-not (Test-Path (Split-Path -Parent $venvDir))) {
            New-Item -ItemType Directory -Path (Split-Path -Parent $venvDir) -Force | Out-Null
        }
        & $script:SystemPython -m venv $venvDir
        Assert-Exit "python -m venv"
        & $venvPy -m pip install --upgrade pip
        Assert-Exit "pip install --upgrade pip"
        & $venvPy -m pip install grpcio-tools
        Assert-Exit "pip install grpcio-tools"
    }
    else {
        Detail "Generator venv present."
    }

    # 3. Generate code when missing/stale/forced (headers count != protos count catches half runs).
    $genHeaders = @(Get-ChildItem -Path (Join-Path $genDir '*.pb.h') -ErrorAction SilentlyContinue)
    $needGen = $Regen -or ($genHeaders.Count -eq 0) -or ($genHeaders.Count -ne $protoFiles.Count)
    if ($needGen) {
        if ($Regen -and (Test-Path $genDir)) {
            Detail "Clearing existing generated files (main\meshtastic\*)."
            Remove-Item -Path (Join-Path $genDir '*') -Force -ErrorAction SilentlyContinue
        }
        if (-not (Test-Path $genDir)) { New-Item -ItemType Directory -Path $genDir -Force | Out-Null }
        Step "Generating nanopb protobuf code ($($protoFiles.Count) protos)"
        $generator = Join-Path $RepoRoot 'components\Nanopb\generator\nanopb_generator.py'
        # Relative paths matched to '-I protobufs' so output lands in main\meshtastic\.
        $protoArgs = $protoFiles | ForEach-Object { "protobufs\meshtastic\$($_.Name)" }
        & $venvPy $generator -S .cpp -I protobufs -D main @protoArgs
        Assert-Exit "nanopb generator"
        $made = @(Get-ChildItem -Path (Join-Path $genDir '*.pb.h') -ErrorAction SilentlyContinue)
        Good "Generated $($made.Count) protobuf headers."
    }
    else {
        Detail "Protobuf code up to date ($($genHeaders.Count)/$($protoFiles.Count))."
    }
}

# --- Build / port / flash / monitor ----------------------------------------------------------

function Invoke-Build {
    if ($Clean) {
        Step "idf.py fullclean"
        idf.py fullclean
        Assert-Exit "idf.py fullclean"
    }
    Step "Building firmware (the first build can take several minutes)"
    idf.py build
    Assert-Exit "idf.py build"
    Good "Build complete."
}

# ESP32-S3 native USB exposes VID 303A. Match the VID + a COM number; never match the friendly
# name's words (it's localized, e.g. the Russian 'Последовательный порт (COM4)').
function Get-EspPorts {
    @(Get-CimInstance Win32_PnPEntity -ErrorAction SilentlyContinue |
        Where-Object { $_.DeviceID -match 'VID_303A' -and $_.Name -match 'COM\d+' } |
        ForEach-Object {
            [pscustomobject]@{
                Port = [regex]::Match($_.Name, 'COM\d+').Value
                Name = $_.Name
            }
        } | Sort-Object Port -Unique)
}

function Resolve-Port {
    if ($Port) {
        if ($Port -notmatch '^COM\d+$') { throw "Invalid -Port '$Port' (expected e.g. COM4)." }
        if (-not (Get-EspPorts | Where-Object { $_.Port -eq $Port })) {
            Caution "$Port is not currently detected as an ESP32-S3; trying it anyway."
        }
        return $Port
    }
    $ports = @(Get-EspPorts)
    if ($ports.Count -eq 0) {
        throw @"
No ESP32-S3 (USB VID 303A) serial device found.
 - Plug the Cardputer into USB-C with a DATA cable (not charge-only).
 - Close any serial monitor / app that may be holding the port.
 - Or specify it explicitly:  .\flash.ps1 -Port COM4
"@
    }
    if ($ports.Count -eq 1) {
        Detail "Found device on $($ports[0].Port) ($($ports[0].Name))."
        return $ports[0].Port
    }
    if ($Yes) {
        throw "Multiple ESP32-S3 devices found; pick one with -Port. Detected: $(($ports | ForEach-Object { $_.Port }) -join ', ')."
    }
    Write-Host "Multiple ESP32-S3 devices found:" -ForegroundColor Yellow
    for ($i = 0; $i -lt $ports.Count; $i++) {
        Write-Host ("  [{0}] {1}  {2}" -f $i, $ports[$i].Port, $ports[$i].Name)
    }
    $sel = Read-Host "Select device number"
    if ($sel -notmatch '^\d+$' -or [int]$sel -ge $ports.Count) { throw "Invalid selection." }
    return $ports[[int]$sel].Port
}

function Confirm-Wipe {
    if ($FlashMode -eq 'App') { return }
    if ($Yes) {
        Caution "-Yes set: full flash will reset NVS to nvs.csv defaults (mesh keys wiped)."
        return
    }
    Write-Host ""
    Write-Host "  ========================== FULL FLASH - NVS WIPE ==========================" -ForegroundColor Yellow
    Write-Host "  A full flash rewrites bootloader + partition table + NVS + ota_data + app."  -ForegroundColor Yellow
    Write-Host "  Your mesh/channel keys and X25519 security keys live in NVS and WILL BE"      -ForegroundColor Red
    Write-Host "  ERASED, replaced by the factory defaults baked from nvs.csv."                 -ForegroundColor Red
    Write-Host ""
    Write-Host "  Back them up FIRST on the device:  Settings -> Export  (writes to the SD card)." -ForegroundColor Yellow
    Write-Host "  Node DB and chat history are SD-backed and will survive."                     -ForegroundColor DarkGray
    Write-Host "  For a routine update that KEEPS your keys, cancel and use:  .\flash.ps1 -AppOnly" -ForegroundColor DarkGray
    Write-Host "  ===========================================================================" -ForegroundColor Yellow
    Write-Host ""
    $ans = Read-Host "Type Y to wipe NVS and full-flash (anything else cancels)"
    if ($ans -notmatch '^(y|yes)$') {
        Write-Host "Cancelled - nothing flashed." -ForegroundColor Cyan
        exit 0
    }
}

function Invoke-Flash {
    param([Parameter(Mandatory)][string] $ResolvedPort)
    if ($FlashMode -eq 'App') {
        if (-not (Test-Path (Join-Path $RepoRoot 'build\flasher_args.json'))) {
            Caution "No prior full build detected - a blank device needs a full flash. If it doesn't boot, re-run without -AppOnly."
        }
        Step "Flashing app partition only (NVS preserved) on $ResolvedPort"
        idf.py -p $ResolvedPort app-flash
        Assert-Exit "idf.py app-flash"
    }
    else {
        Step "Full-flashing $ResolvedPort"
        idf.py -p $ResolvedPort flash
        Assert-Exit "idf.py flash"
    }
    Good "Flash complete - the device will reboot into the new firmware."
}

function Invoke-Monitor {
    param([Parameter(Mandatory)][string] $ResolvedPort)
    Step "Opening serial monitor on $ResolvedPort (exit with Ctrl+])"
    idf.py -p $ResolvedPort monitor   # interactive; a Ctrl+] exit is not a failure
}

function Write-Summary {
    param([string] $ResolvedPort)
    Write-Host ""
    Good "Done."
    if ($ResolvedPort) {
        Write-Host "  Flashed to:   $ResolvedPort  ($FlashMode flash)" -ForegroundColor DarkGray
        Write-Host "  Monitor:      idf.py -p $ResolvedPort monitor   (or re-run with -Monitor)" -ForegroundColor DarkGray
    }
    if ($FlashMode -eq 'Full') {
        Write-Host "  Reminder:     NVS was reset - re-import your keys if you exported them." -ForegroundColor DarkGray
    }
    Write-Host "  Next time:    .\flash.ps1 -AppOnly  keeps NVS keys (routine app update)." -ForegroundColor DarkGray
}

# --- Orchestration (runs at SCRIPT scope so dot-sourced activation persists) -----------------

$OrigLocation = Get-Location
try {
    if ($Help) { Show-Help; exit 0 }

    # Argument precedence / validation (fail fast, before any slow work).
    if ($AppOnly -and $Full) { throw "-AppOnly and -Full are mutually exclusive." }
    $FlashMode = if ($AppOnly) { 'App' } else { 'Full' }
    $doMonitor = [bool]$Monitor
    if ($doMonitor -and $NoFlash) {
        Caution "-Monitor ignored because -NoFlash was given (nothing to monitor)."
        $doMonitor = $false
    }

    Assert-RepoRoot
    Set-Location $RepoRoot

    # Discover the ESP-IDF install from the EIM manifest up front: it drives activation below and
    # doubles as the git / Python fallback source on an otherwise-bare machine.
    $script:IdfInstall = Select-BestIdf (Get-IdfInstallsFromEim)

    # Resolve a Python BEFORE activation (activation changes which 'python' is on PATH).
    $script:SystemPython = Get-SystemPython

    # Activate ESP-IDF. Dot-source at SCRIPT scope so any idf.py function/alias and PATH the
    # profile defines persist for the rest of the run. Shield the vendor profile from this
    # script's StrictMode / Stop preference while sourcing.
    Step "Preparing ESP-IDF environment"
    $activation = Resolve-ActivationScript
    if ($activation) {
        $savedEAP = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        Set-StrictMode -Off
        . $activation
        Set-StrictMode -Version Latest
        $ErrorActionPreference = $savedEAP
        if (-not (Get-Command idf.py -ErrorAction SilentlyContinue)) {
            throw "Activation ran but idf.py is still unavailable. Check that the ESP-IDF paths in tools\activate-idf.ps1 match your install (IDF_PATH / IDF_TOOLS_PATH / IDF_PYTHON_ENV_PATH), or delete that file and re-run from an ESP-IDF PowerShell shell."
        }
    }
    # On a clean machine git may not be on PATH; use the one EIM bundled (from the manifest) so the
    # protobuf clone and idf.py's component manager can run.
    if (-not (Get-Command git -ErrorAction SilentlyContinue) -and
        $script:IdfInstall -and $script:IdfInstall.GitPath -and (Test-Path $script:IdfInstall.GitPath)) {
        $env:PATH = "$(Split-Path -Parent $script:IdfInstall.GitPath);$env:PATH"
        Detail "Using EIM-bundled git: $($script:IdfInstall.GitPath)"
    }

    $idfVersion = (idf.py --version 2>&1 | Out-String).Trim()
    Assert-Exit "idf.py --version"
    Detail $idfVersion
    if ($idfVersion -notmatch '5\.5\.') {
        Caution "This project targets ESP-IDF 5.5.x (tested 5.5.4); building with the above anyway."
    }

    Ensure-Protos

    if ($SetupOnly) {
        Good "Setup complete (-SetupOnly). Run .\flash.ps1 to build & flash."
        exit 0
    }

    Invoke-Build

    if ($NoFlash) {
        Good "Build complete (-NoFlash). Skipping flash."
        Write-Host "  To flash:  .\flash.ps1           (full flash, prompts before wiping NVS)" -ForegroundColor DarkGray
        Write-Host "             .\flash.ps1 -AppOnly  (app only, preserves NVS keys)" -ForegroundColor DarkGray
        exit 0
    }

    $resolvedPort = Resolve-Port
    Confirm-Wipe
    Invoke-Flash -ResolvedPort $resolvedPort
    if ($doMonitor) { Invoke-Monitor -ResolvedPort $resolvedPort }
    Write-Summary -ResolvedPort $resolvedPort
}
catch {
    Write-Host ""
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
finally {
    Set-Location $OrigLocation -ErrorAction SilentlyContinue
}
